version: '3'
services:

  dev-workstation:
    #image: "sysdiglabs/mc-pi-dev"
    image: "hopatechminecraft.azurecr.io/mc-pi-dev"
    container_name: "mc-pi-dev"
    #ports:
    #  - "80:80"
    volumes:
      #- "./src:/usr/src/app"
      - "src:/usr/src/app"
    tty: true
    stdin_open: true
    restart: OnFailure
    links:
     - minecraft-server

  minecraft-server:
    image: "itzg/minecraft-server"
    container_name: "mc-pi-srv"
    domainname: "hopatechminecraft"
    ports:
      - "25565:25565"
      - "4711:4711"
      - "80:80"
    volumes:
      - "data:/data"
      - "plugins:/plugins"
      #- "./data:/data"
      #- "./plugins:/plugins"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "LATEST"
      MEMORY: "4G"
      DEBUG: "true"
    tty: true
    stdin_open: true
    restart: never
    deploy:
      resources:
        reservations:
          memory: 4G

volumes:
  data:
    driver: azure_file
    driver_opts:
      share_name: data
      storage_account_name: hopatechminecraft

  plugins:
    driver: azure_file
    driver_opts:
      share_name: plugins
      storage_account_name: hopatechminecraft

  src:
    driver: azure_file
    driver_opts:
      share_name: src
      storage_account_name: hopatechminecraft